/** English editorial UI strings. Scientific values and source titles remain in their canonical datasets. */
export const content = {
  "FrontierCadence": {
    "text1": "No clean like-for-like benchmark pair stored yet. New capability axes are shown without inventing a synthetic intelligence score.",
    "text2": "Benchmark comparisons are model-family specific. Do not compare bar lengths across unrelated tests.",
    "text3": "(['models']);const[selectedOrg,setSelectedOrg]=useState",
    "text4": "(null);const[zoom,setZoom]=useState(1);const[hoveredEvent,setHoveredEvent]=useState",
    "text5": "78?'left':xPos(year)",
    "text6": "Math.abs(y-year)",
    "text7": "ACCELERATOR / Frontier system",
    "text8": "2012–2022 establishes the technical foundations. From late 2022, release density increases sharply.",
    "text9": "The frontier becomes denser.",
    "text10": "Multiple laboratories release increasingly capable systems across the same period.",
    "text11": ":l.id==='rnd'?",
    "text12": "Select layers to compare drivers on the same 2012→NOW axis. Select a laboratory name to isolate its model trajectory.",
    "text13": "← PREHISTORY / 1956—2011",
    "text14": "FOUNDATIONS / 2012—CHATGPT",
    "text15": "FRONTIER RACE / CHATGPT—NOW",
    "text16": "CHATGPT",
    "text17": "activeLayers.includes(l.id)&&",
    "text18": "=0?(8+labIndex*12.5):92;const showFoundation=d.item.era==='foundation'&&(d.i===0||d.item.date.slice(0,4)!==(density[d.i-1]?.item.date.slice(0,4)??''));return",
    "text19": "Primary source ↗",
    "text20": "Selected milestone gap",
    "text21": "Interval between selected public milestones — not measured research generation time.",
    "text22": "Reading rule",
    "text23": "Release density alone does not establish faster research. The signal becomes stronger only when denser frontier releases coincide with independent capability growth, lower human intervention, persistent recursive gain and shorter validated R&D cycles."
  },
  "EvidenceExplorer": {
    "text1": "02 / Where are we?",
    "text2": "A reading of public evidence, not a forecast and not a probability of AGI.",
    "text3": "What does the evidence say?",
    "text4": "Question",
    "text5": "Evidence count",
    "text6": "s.id===id)).filter(Boolean);return",
    "text7": "Limit / uncertainty",
    "text8": "Sources",
    "text9": "Reading rule",
    "text10": "Unknown is a result.",
    "text11": "When public evidence cannot establish a trend, FEEDBACK keeps the indicator unresolved rather than converting uncertainty into a score."
  },
  "WhatIf": {
    "text1": ".58&&K",
    "text2": "=.55&&gain",
    "text3": "=.28&&compression",
    "text4": "65&&c",
    "text5": "04 / What if?",
    "text6": "A teaching model for exploring dependencies. Not a forecast.",
    "text7": "Change the loop.",
    "text8": "What happens when capability, autonomy or experimental scale changes — while the other bottlenecks remain?",
    "text9": "Reset / baseline",
    "text10": "0?'−':m.compression",
    "text11": "Illustrative generation time",
    "text12": "Binding constraint",
    "text13": "R* is continuous: partial capability can produce bounded gains. τ only begins to compress when those gains outweigh residual loop friction.",
    "text14": "Scale is not capability",
    "text15": "More experiments. Same bottleneck. No intelligence explosion. Research capability and judgement are still limiting the loop.",
    "text16": "Show the model",
    "text17": "C · K · N · R* · τ",
    "text18": "A deliberately bounded teaching model.",
    "text19": "Effective research capacity depends on capability and loop closure. Recursive gain appears only after a threshold and is moderated by scale. Cycle compression is then reduced by residual human and process friction.",
    "text20": "Interpretation rule",
    "text21": "The simulator demonstrates dependencies, not calibrated probabilities. Coefficients are illustrative and must not be read as empirical estimates.",
    "text22": "Next research requirement",
    "text23": "Replace illustrative coefficients only when longitudinal AI-R&D cycle data can support calibration."
  },
  "SourcesMethods": {
    "text1": "09 / Sources & methods",
    "text2": "How evidence enters FEEDBACK, how it is classified and what the observatory does not claim.",
    "text3": "Show the receipts.",
    "text4": "Every public reading should be traceable to a source, an evidence type and an explicit limitation.",
    "text5": "Method / inclusion",
    "text6": "Evidence before narrative.",
    "text7": "Include",
    "text8": "Direct evaluations, empirical papers, systematic surveys and explicit models that bear on C, K, R or τ.",
    "text9": "Separate",
    "text10": "Observation, estimate, hypothesis and scenario. Publication date never substitutes for observation date.",
    "text11": "Record",
    "text12": "Direction, confidence, limitation and primary source. Contrary evidence stays visible.",
    "text13": "Update",
    "text14": "Readings change when discriminating evidence changes. Unknown is preserved when evidence remains insufficient.",
    "text15": "Primary record / external source",
    "text16": "Scope / v0.1",
    "text17": "What FEEDBACK is not.",
    "text18": "FEEDBACK is not an AGI countdown, a probability forecast, a leaderboard or a claim that recursive acceleration is occurring.",
    "text19": "It is an evolving public framework for asking whether the observable conditions associated with recursive AI-R&D acceleration are becoming more strongly supported.",
    "text20": "Version discipline",
    "text21": "Changes to definitions, evidence classification or model assumptions should be versioned separately from changes in the underlying evidence record."
  },
  "QuantSignals": {
    "text1": "SIGNALS / Quantitative lenses",
    "text2": "Historical context becomes useful when release cadence is compared with independent capability measurements.",
    "text3": "Is anything measurable accelerating?",
    "text4": "TASK HORIZON",
    "text5": "BENCHMARK PRESSURE",
    "text6": "SCHEMATIC TREND — historical points are provisional visual anchors, not authoritative METR values. Use METR's live dataset for measurement.",
    "text7": "Stanford AI Index / OSWorld",
    "text8": "Agent computer-use performance rose sharply in 2025. Stanford also reports that difficult benchmarks are increasingly saturated in months rather than years.",
    "text9": "Fast benchmark progress supports C ↑. It does not establish K → 1, R &gt; 0 or τ ↓.",
    "text10": "Interpretation",
    "text11": "The useful comparison is not “models are released faster, therefore intelligence is exploding.” It is whether independent capability measures rise while human intervention falls, recursive gains persist and validated improvement cycles compress."
  },
  "ChangeOurMind": {
    "text1": "08 / What would change our mind?",
    "text2": "Explicit update criteria reduce hindsight bias.",
    "text3": "A claim must be able to lose.",
    "text4": "For every indicator, FEEDBACK states what would strengthen the claim — and what would weaken it.",
    "text5": "Would strengthen",
    "text6": "Would weaken",
    "text7": "Current reading",
    "text8": "Update rule",
    "text9": "New evidence can move an indicator in either direction. “Unknown” remains valid when the evidence cannot discriminate."
  },
  "TheModel": {
    "text1": "07 / The model",
    "text2": "A measurement framework first. A mathematical model only where assumptions are explicit.",
    "text3": "Four variables.",
    "text4": "One question.",
    "text5": "Is the feedback loop becoming more capable, more closed, recursively productive — and faster?",
    "text6": "Operational definition",
    "text7": "Watch",
    "text8": "Relationship / not an equation",
    "text9": "C ↑",
    "text10": "K ↑",
    "text11": "R &gt; 0",
    "text12": "The arrows are hypotheses to test, not identities.",
    "text13": "Higher capability may help close the loop. Greater closure may enable recursive gains. Recursive gains may shorten development cycles. None of those implications is guaranteed.",
    "text14": "What If? / teaching model",
    "text15": "Illustrative, not fitted.",
    "text16": "The simulator deliberately maps C, K and scale to bounded R* and a signed change in τ. Its coefficients are chosen to make dependencies visible. They are not estimates derived from observed AI-R&D data.",
    "text17": "FEEDBACK will only promote a relationship from teaching assumption to empirical model when longitudinal evidence can constrain it.",
    "text18": "Core test",
    "text19": "The strongest signal is not C ↑. It is persistent, bottleneck-adjusted τ ↓ across successive useful improvements."
  },
  "EvidenceTimeline": {
    "text1": "06 / Evidence",
    "text2": "A chronological view of the public record behind FEEDBACK's current reading.",
    "text3": "Watch the evidence move.",
    "text4": "Source",
    "text5": "Timeline rule",
    "text6": "Publication date is not observation date. Theoretical models and scenarios belong in the record, but they are not plotted as empirical changes in the world."
  },
  "ThreeFutures": {
    "text1": "05 / Three futures",
    "text2": "Three trajectories. No probabilities assigned.",
    "text3": "Same system.",
    "text4": "Different dynamics.",
    "text5": "Illustrative τ / generation",
    "text6": "What would distinguish it?",
    "text7": "Do not infer",
    "text8": "Scenario discipline / These are conditional trajectories, not forecasts, timelines or probability estimates."
  },
  "MissingGates": {
    "text1": "03 / What's missing?",
    "text2": "The gap between stronger models and a self-accelerating research system.",
    "text3": "Capability is not acceleration.",
    "text4": "Each transition has to clear a different bottleneck. Evidence for one does not automatically transfer to the next.",
    "text5": "Transition",
    "text6": "Interpretation",
    "text7": "What would need to change?",
    "text8": "Gate",
    "text9": "Current bottleneck",
    "text10": "The final arrow is unproven.",
    "text11": "We have evidence of rising capability and bounded recursive improvement. We do not yet have robust public evidence that successive useful AI-R&D generations are arriving faster and faster.",
    "text12": "FEEDBACK test",
    "text13": "C ↑ does not imply K → 1.",
    "text14": "K → 1 does not imply R &gt; 0.",
    "text15": "R &gt; 0 does not imply τ ↓.",
    "text16": "An intelligence-explosion claim needs evidence across the chain, not evidence from its strongest link."
  },
  "TheLoop": {
    "text1": "01 / The loop",
    "text2": "Four steps explain the mechanism. No prediction is required.",
    "text3": "How could the loop close?",
    "text4": "Cycle 1",
    "text5": "Cycle 2",
    "text6": "Cycle 3",
    "text7": "Cycle 4",
    "text8": "Illustration only — not a forecast.",
    "text9": "If each useful improvement makes the next useful improvement easier — and the cycle keeps shortening — the dynamics have changed.",
    "text10": "FEEDBACK watches for evidence of that transition. It does not assume that it will happen."
  }
} as const;
