import React,{useEffect,useMemo,useState}from'react';

type Metric={label:string,previous:number,current:number,unit?:string};
type M={year:number,date:string,name:string,org:string,type:'architecture'|'model'|'product'|'reasoning'|'open';why:string,url:string,era:'foundation'|'race',compareTo?:string,metrics?:Metric[],capabilities?:string[]};
const milestones:M[]=[
{year:2012.92,date:'2012',name:'AlexNet',org:'University of Toronto',type:'architecture',era:'foundation',why:'GPU-trained deep convolutional networks decisively changed large-scale vision.',url:'https://papers.nips.cc/paper/4824-imagenet-classification-with-deep-convolutional-neural-networks'},
{year:2016.07,date:'2016-01',name:'AlphaGo',org:'Google DeepMind',type:'reasoning',era:'foundation',why:'Deep neural networks, search and self-play defeated a professional Go player.',url:'https://www.nature.com/articles/nature16961'},
{year:2017.45,date:'2017-06',name:'Transformer',org:'Google',type:'architecture',era:'foundation',why:'Attention became the architecture behind the modern language-model era.',url:'https://arxiv.org/abs/1706.03762'},
{year:2018.45,date:'2018-06',name:'GPT',org:'OpenAI',type:'model',era:'foundation',why:'Generative pre-training demonstrated broad transfer from unsupervised language modelling.',url:'https://cdn.openai.com/research-covers/language-unsupervised/language_understanding_paper.pdf'},
{year:2019.12,date:'2019-02-14',name:'GPT-2',org:'OpenAI',type:'model',era:'foundation',why:'Scaling a transformer language model produced strong zero-shot behaviour.',url:'https://openai.com/index/better-language-models/'},
{year:2020.41,date:'2020-05-28',name:'GPT-3',org:'OpenAI',type:'model',era:'foundation',why:'Few-shot prompting became a central capability paradigm.',url:'https://openai.com/index/language-models-are-few-shot-learners/'},
{year:2022.91,date:'2022-11-30',name:'ChatGPT',org:'OpenAI',type:'product',era:'race',why:'The frontier becomes a mass interactive product and a common reference point for subsequent competition.',url:'https://openai.com/index/chatgpt/',capabilities:['dialogue','RLHF','mass deployment']},
{year:2023.20,date:'2023-03-14',name:'Claude 1',org:'Anthropic',type:'model',era:'race',why:'Claude moves from closed alpha to broad chat and API availability.',url:'https://www.anthropic.com/news/introducing-claude',capabilities:['dialogue','coding','steerability']},
{year:2023.201,date:'2023-03-14',name:'GPT-4',org:'OpenAI',type:'model',era:'race',why:'A major jump in difficult reasoning, exams and multimodality.',url:'https://openai.com/index/gpt-4-research/',compareTo:'GPT-3.5',metrics:[{label:'MMLU',previous:70,current:86.4,unit:'%'},{label:'HumanEval',previous:48.1,current:67,unit:'%'},{label:'GSM8K',previous:57.1,current:92,unit:'%'}],capabilities:['vision input','stronger reasoning','coding']},
{year:2023.53,date:'2023-07-11',name:'Claude 2',org:'Anthropic',type:'model',era:'race',why:'Claude 2 improves coding, mathematics and reasoning while extending context length.',url:'https://www.anthropic.com/research/claude-2',compareTo:'Claude 1.3',metrics:[{label:'Bar exam MCQ',previous:73,current:76.5,unit:'%'}],capabilities:['100K context','coding','reasoning']},
{year:2023.74,date:'2023-09-27',name:'Mistral 7B',org:'Mistral AI',type:'model',era:'race',why:'A compact open-weight model demonstrates strong performance with an efficiency-focused architecture.',url:'https://mistral.ai/news/announcing-mistral-7b',capabilities:['open weights','efficiency','local deployment']},
{year:2023.84,date:'2023-11-03',name:'Grok 1',org:'xAI',type:'model',era:'race',why:'The first Grok beta follows two months of training and adds real-time knowledge through X.',url:'https://x.ai/news/grok',capabilities:['real-time knowledge','reasoning','coding']},
{year:2023.93,date:'2023-12-06',name:'Gemini 1.0',org:'Google DeepMind',type:'model',era:'race',why:'A natively multimodal model family spans text, code, audio, image and video.',url:'https://blog.google/innovation-and-ai/technology/ai/google-gemini-ai/',capabilities:['native multimodality','Ultra / Pro / Nano']},
{year:2024.24,date:'2024-03-28',name:'Grok 1.5',org:'xAI',type:'model',era:'race',why:'Five months after Grok 1, xAI reports large gains in reasoning, mathematics, coding and a 128K context window.',url:'https://x.ai/news/grok-1.5',compareTo:'Grok 1',metrics:[{label:'MMLU',previous:73,current:81.3,unit:'%'},{label:'GSM8K',previous:62.9,current:90,unit:'%'},{label:'HumanEval',previous:63.2,current:74.1,unit:'%'}],capabilities:['128K context','reasoning','coding']},
{year:2024.12,date:'2024-02-15',name:'Gemini 1.5 Pro',org:'Google DeepMind',type:'model',era:'race',why:'Long-context understanding becomes a new competitive axis.',url:'https://blog.google/innovation-and-ai/products/google-gemini-next-generation-model-february-2024/',compareTo:'Gemini 1.0 Ultra',capabilities:['1M-token context','multimodal reasoning','MoE efficiency']},
{year:2024.17,date:'2024-03-04',name:'Claude 3 Opus',org:'Anthropic',type:'model',era:'race',why:'Anthropic reports frontier performance across knowledge, reasoning and mathematics.',url:'https://www.anthropic.com/research/claude-3-family',compareTo:'Claude 2.1',capabilities:['vision','GPQA','stronger reasoning']},
{year:2024.36,date:'2024-05-13',name:'GPT-4o',org:'OpenAI',type:'model',era:'race',why:'Native real-time multimodality brings text, vision and audio into one flagship system.',url:'https://openai.com/index/hello-gpt-4o/',compareTo:'GPT-4',capabilities:['native audio','vision','lower latency']},
{year:2024.62,date:'2024-08-13',name:'Grok 2',org:'xAI',type:'model',era:'race',why:'xAI reaches the contemporary frontier across reasoning, coding and vision, only months after Grok 1.5.',url:'https://x.ai/news/grok-2',compareTo:'Grok 1.5',metrics:[{label:'GPQA',previous:35.9,current:56,unit:'%'},{label:'MMLU',previous:81.3,current:87.5,unit:'%'},{label:'HumanEval',previous:74.1,current:88.4,unit:'%'}],capabilities:['vision','reasoning','coding']},
{year:2024.70,date:'2024-09-12',name:'o1',org:'OpenAI',type:'reasoning',era:'race',why:'Test-time reasoning opens a distinct scaling axis beyond pre-training.',url:'https://openai.com/index/learning-to-reason-with-llms/',compareTo:'GPT-4o',capabilities:['test-time reasoning','math','science','coding']},
{year:2024.945,date:'2024-12-11',name:'Gemini 2.0 Flash',org:'Google DeepMind',type:'model',era:'race',why:'Google explicitly frames Gemini 2.0 as the move into the agentic era, adding native multimodal output and tool use.',url:'https://blog.google/innovation-and-ai/models-and-research/google-deepmind/google-gemini-ai-update-december-2024/',compareTo:'Gemini 1.5 Pro',capabilities:['native tool use','multimodal output','agentic prototypes']},
{year:2024.99,date:'2024-12-26',name:'DeepSeek-V3',org:'DeepSeek',type:'open',era:'race',why:'A strong open model increases competitive pressure at the frontier.',url:'https://api-docs.deepseek.com/updates/',capabilities:['open weights','coding','math']},
{year:2025.23,date:'2025-03-25',name:'Gemini 2.5 Pro',org:'Google DeepMind',type:'reasoning',era:'race',why:'Thinking becomes native to the Gemini generation, with stronger reasoning and coding and a 1M-token context window.',url:'https://blog.google/innovation-and-ai/models-and-research/google-deepmind/gemini-model-thinking-updates-march-2025/',compareTo:'Gemini 2.0',capabilities:['thinking','reasoning','coding','1M context']},
{year:2025.14,date:'2025-02-19',name:'Grok 3',org:'xAI',type:'reasoning',era:'race',why:'xAI adds a new reasoning generation with substantially expanded pretraining and explicit reasoning models.',url:'https://x.ai/news/grok-3',compareTo:'Grok 2',capabilities:['reasoning','agents','expanded pretraining']},
{year:2025.05,date:'2025-01-20',name:'DeepSeek-R1',org:'DeepSeek',type:'reasoning',era:'race',why:'Open reasoning models demonstrate performance reported on par with o1 on math, code and reasoning tasks.',url:'https://deepseek.com/en/news/deepseek-r1/',compareTo:'DeepSeek-V3',capabilities:['large-scale RL','reasoning','open weights']},
{year:2025.32,date:'2025-04-29',name:'Qwen3',org:'Alibaba / Qwen',type:'reasoning',era:'race',why:'Qwen adds a hybrid thinking/non-thinking generation to the open frontier.',url:'https://qwenlm.github.io/blog/qwen3/',capabilities:['hybrid reasoning','open weights','multilingual']},
{year:2025.53,date:'2025-07-11',name:'Kimi K2',org:'Moonshot AI',type:'model',era:'race',why:'Kimi K2 pushes open-weight models toward agentic tool use and coding.',url:'https://moonshotai.github.io/Kimi-K2/',capabilities:['agentic tasks','coding','open weights']},
{year:2025.57,date:'2025-07-28',name:'GLM-4.5',org:'Z.ai',type:'model',era:'race',why:'GLM unifies reasoning, coding and agentic capabilities in an open-weight frontier model.',url:'https://z.ai/blog/glm-4.5',capabilities:['reasoning','coding','agents','open weights']},
{year:2025.52,date:'2025-07-09',name:'Grok 4',org:'xAI',type:'reasoning',era:'race',why:'xAI scales reinforcement learning to pretraining scale and adds native tool use and real-time search.',url:'https://x.ai/news/grok-4',compareTo:'Grok 3',capabilities:['native tools','real-time search','scaled RL']},
{year:2025.64,date:'2025-08-21',name:'DeepSeek V3.1',org:'DeepSeek',type:'model',era:'race',why:'DeepSeek explicitly calls V3.1 its first step toward the agent era: hybrid thinking, faster reasoning and stronger tool use.',url:'https://api-docs.deepseek.com/news/news250821/',compareTo:'DeepSeek-R1',capabilities:['hybrid reasoning','agents','tool use','128K context']},
{year:2025.60,date:'2025-08-07',name:'GPT-5',org:'OpenAI',type:'model',era:'race',why:'A unified system combines fast responses, deeper reasoning and routing for agentic work.',url:'https://openai.com/index/introducing-gpt-5/',compareTo:'GPT-4o / o-series',capabilities:['routing','agentic work','reasoning']},
{year:2025.88,date:'2025-11-18',name:'Gemini 3',org:'Google DeepMind',type:'model',era:'race',why:'Google combines advanced reasoning, multimodal understanding and agentic capabilities in a new Gemini generation.',url:'https://blog.google/products-and-platforms/products/gemini/gemini-3/',compareTo:'Gemini 2.5 Pro',capabilities:['reasoning','multimodality','agents','generative UI']},
{year:2025.91,date:'2025-12-01',name:'DeepSeek V3.2',org:'DeepSeek',type:'reasoning',era:'race',why:'Reasoning-first model built for agents, integrating thinking directly into tool use.',url:'https://api-docs.deepseek.com/news/news251201/',compareTo:'DeepSeek V3.1',capabilities:['thinking in tool use','agents','reasoning']},
{year:2025.915,date:'2025-12-02',name:'Mistral Large 3',org:'Mistral AI',type:'model',era:'race',why:'A new open-weight multimodal MoE generation returns Mistral to the large-model frontier.',url:'https://mistral.ai/news/mistral-3/',compareTo:'Mistral Large',capabilities:['open weights','multimodal','MoE','multilingual']},
{year:2026.115,date:'2026-02-12',name:'GLM-5',org:'Z.ai',type:'model',era:'race',why:'GLM scales toward complex systems engineering and long-horizon agentic tasks.',url:'https://z.ai/blog/glm-5',compareTo:'GLM-4.5',capabilities:['long-horizon agents','systems engineering','open weights']},
{year:2026.44,date:'2026-06-09',name:'Claude Fable 5',org:'Anthropic',type:'model',era:'race',why:'Anthropic moves long-horizon agentic work to the center of the frontier: complex multi-day knowledge work, coding and self-verification.',url:'https://www.anthropic.com/news/claude-fable-5-mythos-5',compareTo:'Claude Opus 4.8',capabilities:['long-horizon agency','1M context','self-verification','coding']},
{year:2026.67,date:'2026-09-01',name:'Claude Fable 5.1',org:'Anthropic',type:'model',era:'race',why:'A rapid follow-on strengthens long-running agentic coding, multistep research and professional document work.',url:'https://platform.claude.com/docs/en/models/fable-5-1/overview',compareTo:'Claude Fable 5',capabilities:['agentic coding','multistep research','1M context']},
{year:2026.31,date:'2026-04-23',name:'GPT-5.5',org:'OpenAI',type:'model',era:'race',why:'Greater autonomous work across coding, research, analysis and computer workflows.',url:'https://openai.com/index/introducing-gpt-5-5/',compareTo:'GPT-5',capabilities:['autonomous work','computer use','research']},
{year:2026.61,date:'2026-08-12',name:'Grok 4.6',org:'xAI',type:'model',era:'race',why:'Long-running agents and ambitious interactive work become a stated frontier target.',url:'https://x.ai/news/grok-4-6',compareTo:'Grok 4.5',capabilities:['long-running agents','coding','knowledge work']},
{year:2026.67,date:'2026-09-03',name:'GPT-6 Astra',org:'OpenAI',type:'model',era:'race',why:'A new frontier generation across computer use, software engineering, science and professional work.',url:'https://openai.com/index/gpt-6-astra/',compareTo:'GPT-5.5',capabilities:['computer use','science','software engineering']},
{year:2026.72,date:'2026-09-22',name:'GPT-6 Sol / Luna',org:'OpenAI',type:'model',era:'race',why:'Frontier capability spreads into faster and lower-cost members of the GPT-6 family.',url:'https://openai.com/index/introducing-gpt-6-sol-and-luna/',compareTo:'GPT-6 Astra',capabilities:['speed','cost efficiency','frontier family']}
];
const min=2012,max=2026.8,pivot=2022.91;
const pos=(y:number,expanded:boolean)=>{const split=expanded?24:62;return y<=pivot?((y-min)/(pivot-min))*split:split+((y-pivot)/(max-pivot))*(100-split)};


const labs=['OpenAI','Anthropic','Google DeepMind','xAI','DeepSeek','Mistral AI','China / Open Frontier'] as const;
const labOf=(m:M)=>m.org==='Google'? 'Google DeepMind':['Alibaba / Qwen','Moonshot AI','Z.ai'].includes(m.org)?'China / Open Frontier':m.org;

function Delta({m}:{m:M}){const[open,setOpen]=useState(false);if(m.era!=='race')return null;return <div className="mt-8 border-t dz-rule pt-6"><button className="delta-toggle dz-meta bg-transparent dz-text border dz-rule px-4 py-3 cursor-pointer" onClick={()=>setOpen(v=>!v)}>{open?'CLOSE':'OPEN'} CAPABILITY DELTA {open?'−':'+'}</button>{open&&<div className="mt-6"><div className="flex flex-wrap gap-2">{m.capabilities?.map(x=><span key={x} className="dz-meta border dz-rule px-3 py-2">{x}</span>)}</div>{m.compareTo&&<p className="dz-meta mt-6">Compared with / {m.compareTo}</p>}{m.metrics?.length?<div className="mt-5 space-y-5">{m.metrics.map(q=><div key={q.label}><div className="flex justify-between gap-4 dz-meta"><span>{q.label}</span><span>{q.previous}{q.unit} → {q.current}{q.unit}</span></div><div className="delta-bars mt-2"><span style={{width:Math.min(100,q.previous)+'%'}}/><span className="current" style={{width:Math.min(100,q.current)+'%'}}/></div></div>)}</div>:<p className="dz-body mt-5">No clean like-for-like benchmark pair stored yet. New capability axes are shown without inventing a synthetic intelligence score.</p>}<p className="dz-meta mt-6">Benchmark comparisons are model-family specific. Do not compare bar lengths across unrelated tests.</p></div>}</div>}

type LayerId='models'|'agents'|'compute'|'infrastructure'|'capital'|'rnd';
const layers:{id:LayerId;label:string;relation:string}[]=[
{id:'models',label:'Models',relation:'C / frontier capability'},
{id:'agents',label:'Agents',relation:'C→K / tool use and autonomy'},
{id:'compute',label:'Compute',relation:'Exogenous capability input'},
{id:'infrastructure',label:'Infrastructure',relation:'Scale, clusters and energy'},
{id:'capital',label:'Capital',relation:'Resource mobilisation'},
{id:'rnd',label:'R&D Loop',relation:'K→R→τ / recursive improvement'}];

type LayerEvent={year:number,date:string,layer:Exclude<LayerId,'models'>,name:string,org:string,why:string,url:string};
const layerEvents:LayerEvent[]=[
{year:2020.37,date:'2020-05-14',layer:'compute',name:'A100 / Ampere',org:'NVIDIA',why:'A100 marks a major data-center acceleration step for AI training and inference.',url:'https://nvidianews.nvidia.com/news/nvidias-new-ampere-data-center-gpu-in-full-production'},
{year:2022.22,date:'2022-03-22',layer:'compute',name:'H100 / Hopper',org:'NVIDIA',why:'Hopper introduces Transformer Engine and a new generation of large-model acceleration.',url:'https://nvidianews.nvidia.com/news/nvidia-announces-hopper-architecture-the-next-generation-of-accelerated-computing'},
{year:2023.37,date:'2023-05-10',layer:'compute',name:'TPU v5e',org:'Google',why:'Google expands purpose-built TPU infrastructure for large-scale generative-AI training and inference.',url:'https://cloud.google.com/blog/products/compute/introducing-cloud-tpu-v5e-and-a3-gpus'},
{year:2023.45,date:'2023-06-13',layer:'agents',name:'Function calling',org:'OpenAI',why:'Models can select structured calls to external tools and APIs.',url:'https://openai.com/index/function-calling-and-other-api-updates/'},
{year:2023.72,date:'2023-09-25',layer:'agents',name:'AutoGen',org:'Microsoft Research',why:'A framework formalizes conversational multi-agent applications built from cooperating LLM agents.',url:'https://www.microsoft.com/en-us/research/project/autogen/'},
{year:2024.21,date:'2024-03-18',layer:'compute',name:'Blackwell / GB200',org:'NVIDIA',why:'Blackwell moves frontier AI compute toward rack-scale systems for trillion-parameter workloads.',url:'https://investor.nvidia.com/news/press-release-details/2024/NVIDIA-Blackwell-Platform-Arrives-to-Power-a-New-Era-of-Computing/'},
{year:2024.81,date:'2024-10-22',layer:'agents',name:'Computer use',org:'Anthropic',why:'Claude can perceive and operate graphical computer interfaces through cursor, click and typing actions.',url:'https://www.anthropic.com/news/developing-computer-use'},
{year:2024.90,date:'2024-11-25',layer:'agents',name:'Model Context Protocol',org:'Anthropic',why:'An open protocol standardizes connections between AI assistants, data sources and tools.',url:'https://www.anthropic.com/news/model-context-protocol'},
{year:2024.94,date:'2024-12-11',layer:'agents',name:'Project Mariner',org:'Google DeepMind',why:'A research prototype explores agents that understand and act in browser interfaces.',url:'https://blog.google/technology/google-deepmind/google-gemini-ai-update-december-2024/'},
{year:2025.06,date:'2025-01-21',layer:'infrastructure',name:'Stargate',org:'OpenAI / SoftBank / Oracle / MGX',why:'A planned $500B four-year AI-infrastructure buildout marks a step change in announced deployment scale.',url:'https://openai.com/index/announcing-the-stargate-project/'},
{year:2025.06,date:'2025-01-23',layer:'agents',name:'Operator',org:'OpenAI',why:'A computer-using agent executes multi-step browser tasks and can self-correct during execution.',url:'https://openai.com/index/introducing-operator/'},
{year:2025.47,date:'2025-06-12',layer:'agents',name:'Claude Code',org:'Anthropic',why:'Coding agents move from assistance toward sustained tool-using software-engineering work.',url:'https://www.anthropic.com/claude-code'},
{year:2026.20,date:'2026-03',layer:'compute',name:'Vera Rubin',org:'NVIDIA',why:'Rubin extends rack-scale AI infrastructure toward reasoning and agentic workloads beyond Blackwell.',url:'https://www.nvidia.com/en-us/data-center/vera-rubin/'},
{year:2026.60,date:'2026',layer:'rnd',name:'AIRA',org:'Meta',why:'An AI research-agent line targets longer autonomous experimental research workflows.',url:'https://ai.meta.com/research/'},
{year:2026.73,date:'2026-09-22',layer:'rnd',name:'AI-R&D acceleration evaluation',org:'METR',why:'Independent evaluation finds limited R&D automation and some acceleration while full AI-R&D automation remains unsupported.',url:'https://metr.org/'}
];

const prehistory=[
{date:'1956',name:'Dartmouth',note:'Artificial intelligence is established as a research field.'},
{date:'1986',name:'Backpropagation',note:'Multilayer neural-network learning becomes practical.'},
{date:'1997',name:'Deep Blue',note:'IBM defeats the reigning world chess champion.'},
{date:'2006',name:'Deep learning',note:'Deep neural-network research re-emerges.'},
{date:'2011',name:'Watson',note:'Large-scale question answering reaches a mass audience.'}
];

export function FrontierCadence(){
 const[idx,setIdx]=useState(0);const[playing,setPlaying]=useState(false);const[showPrehistory,setShowPrehistory]=useState(false);const[activeLayers,setActiveLayers]=useState<LayerId[]>(['models']);const[selectedOrg,setSelectedOrg]=useState<string|null>(null);const[zoom,setZoom]=useState(1);const[hoveredEvent,setHoveredEvent]=useState<string|null>(null);
 useEffect(()=>{if(!playing)return;const id=window.setInterval(()=>setIdx(i=>i>=milestones.length-1?0:i+1),900);return()=>window.clearInterval(id)},[playing]);
 const m=milestones[idx]??milestones[milestones.length-1]!;const expanded=m.era==='race';const prev=idx?(milestones[idx-1]??null):null;
 const months=prev?Math.max(1,Math.round((m.year-prev.year)*12)):null;const angle=months==null?0:Math.min(months,48)/48*300-150;
 const density=useMemo(()=>milestones.map((item,i)=>({item,i})),[]);const viewStart=2012;const viewEnd=2027;const zoomPos=(year:number)=>{const focus=m.year;const span=(viewEnd-viewStart)/zoom;const lo=Math.max(viewStart,Math.min(viewEnd-span,focus-span/2));return Math.max(0,Math.min(100,(year-lo)/span*100))};const xPos=(year:number)=>zoom>1?zoomPos(year):pos(year,expanded);const tooltipSide=(year:number)=>xPos(year)>78?'left':xPos(year)<16?'right':'right';
 return <section id="cadence" className="border-t dz-rule relative z-10"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16 sm:py-24">
  <div className="grid grid-cols-6 lg:grid-cols-12 gap-x-4 gap-y-10"><div className="col-span-6 lg:col-span-3"><p className="dz-meta">ACCELERATOR / Frontier system</p><p className="dz-body mt-5 max-w-xs">2012–2022 establishes the technical foundations. From late 2022, release density increases sharply.</p></div><div className="col-span-6 lg:col-span-8 lg:col-start-5"><h2 className="dz-h2 text-5xl sm:text-7xl lg:text-8xl">The frontier becomes denser.</h2><p className="dz-body-strong text-xl sm:text-2xl mt-8 max-w-3xl">Multiple laboratories release increasingly capable systems across the same period.</p></div></div>
  <div className="mt-16 sm:mt-24 border-y dz-rule py-8"><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex gap-2"><button onClick={()=>setPlaying(!playing)} className="cadence-control dz-meta border dz-rule px-4 py-3 bg-transparent dz-text cursor-pointer">{playing?'PAUSE Ⅱ':'PLAY ▶'}</button><button onClick={()=>{setPlaying(false);setIdx(0)}} className="cadence-control dz-meta border dz-rule px-4 py-3 bg-transparent dz-text cursor-pointer">2012 ↺</button></div><p className="dz-meta">{m.date} / {m.org}</p></div>
   <div className="time-layers mt-8" aria-label="Timeline layers">{layers.map(l=>{const active=activeLayers.includes(l.id);return <button key={l.id} data-layer={l.id} data-active={active} onClick={()=>setActiveLayers(v=>l.id==='models'?v:(v.includes(l.id)?v.filter(x=>x!==l.id):[...v,l.id]))}><span>{l.label}</span><em>{l.relation}</em></button>})}</div>
   <p className="dz-meta mt-3">Select layers to compare drivers on the same 2012→NOW axis. Select a laboratory name to isolate its model trajectory.</p>
   <div className="prehistory-wrap mt-8"><button className="prehistory-toggle dz-meta" onClick={()=>setShowPrehistory(!showPrehistory)} aria-expanded={showPrehistory}>← PREHISTORY / 1956—2011 <span>{showPrehistory?'−':'+'}</span></button>{showPrehistory&&<div className="prehistory-panel">{prehistory.map(x=><div className="prehistory-item" key={x.date}><span className="dz-meta">{x.date}</span><strong>{x.name}</strong><p className="dz-body">{x.note}</p></div>)}</div>}</div>
   <div className={'race-labels mt-10 '+(expanded?'expanded':'')}><span>FOUNDATIONS / 2012—CHATGPT</span><span>FRONTIER RACE / CHATGPT—NOW</span></div>
   <div className={'cadence-track race-track race-map mt-3 relative border-b dz-rule '+(expanded?'is-race':'')} aria-label="AI frontier timeline"><div className="race-pivot" style={{left:xPos(pivot)+'%'}}><span>CHATGPT<br/>30.11.22</span></div>{expanded&&<div className="lab-lanes">{labs.map((lab,li)=><div className="lab-lane" data-active={labOf(m)===lab||selectedOrg===lab} data-selected={selectedOrg===lab} key={lab} style={{top:(8+li*12.5)+'%'}}><button type="button" onClick={()=>setSelectedOrg(v=>v===lab?null:lab)} aria-pressed={selectedOrg===lab}>{lab}</button><i style={{left:pos(pivot,expanded)+'%'}}/></div>)}</div>}<div className="thematic-rails">{layers.filter(l=>l.id!=='models').map((l,li)=>activeLayers.includes(l.id)&&<div className="thematic-rail" data-layer={l.id} key={l.id} style={{bottom:(8+li*5.2)+'%'}}><span>{l.label}</span>{layerEvents.filter(e=>e.layer===l.id).map(e=><a key={e.date+e.name} href={e.url} target="_blank" rel="noreferrer" className="thematic-point" data-org-match={!selectedOrg||e.org.includes(selectedOrg)||selectedOrg.includes(e.org)} data-tooltip-side={tooltipSide(e.year)} data-hovered={hoveredEvent===e.date+e.name} onMouseEnter={()=>setHoveredEvent(e.date+e.name)} onMouseLeave={()=>setHoveredEvent(null)} onFocus={()=>setHoveredEvent(e.date+e.name)} onBlur={()=>setHoveredEvent(null)} style={{left:xPos(e.year)+'%'}} aria-label={e.name+' · '+e.org+' · '+e.date}><i/><span className="thematic-tooltip"><strong>{e.name}</strong><em>{e.org} · {e.date}</em></span></a>)}</div>)}</div>{density.map(d=>{const labIndex=labs.indexOf(labOf(d.item) as typeof labs[number]);const top=expanded&&d.item.era==='race'&&labIndex>=0?(8+labIndex*12.5):92;const showFoundation=d.item.era==='foundation'&&(d.i===0||d.item.date.slice(0,4)!==(density[d.i-1]?.item.date.slice(0,4)??''));return <button key={d.i} onClick={()=>{setPlaying(false);setIdx(d.i)}} className="cadence-point" data-era={d.item.era} data-active={d.i===idx} data-org-match={!selectedOrg||labOf(d.item)===selectedOrg} style={{left:xPos(d.item.year)+'%',top:top+'%'}} aria-label={d.item.name} title={d.item.name+' — '+d.item.date}><span className="cadence-dot"/>{showFoundation&&<span className="cadence-year">{d.item.date.slice(0,4)}</span>}{expanded&&d.item.era==='race'&&d.i===idx&&<span className={'active-model-label '+(labIndex%2?'label-below':'label-above')}><strong>{d.item.name}</strong><em>{d.item.date} · {d.item.org}</em></span>}</button>})}</div>
   <input className="cadence-range mt-8 w-full" type="range" min="0" max={milestones.length-1} value={idx} onChange={e=>{setPlaying(false);setIdx(Number(e.target.value))}} aria-label="Navigate AI milestones"/></div>
  <div className="grid lg:grid-cols-12 border-b dz-rule"><div className="lg:col-span-7 py-10 lg:pr-10 lg:border-r dz-rule"><p className="dz-meta">{String(idx+1).padStart(2,'0')} / {m.org} / {m.type}</p><h3 className="dz-h2 text-5xl sm:text-7xl mt-4">{m.name}</h3><p className="dz-body-strong text-xl mt-6 max-w-2xl">{m.why}</p><a href={m.url} target="_blank" rel="noreferrer" className="inline-block dz-meta mt-8 cadence-source">Primary source ↗</a><Delta m={m}/></div>
   <div className="lg:col-span-5 py-10 lg:pl-10 border-t lg:border-t-0 dz-rule flex flex-col sm:flex-row lg:flex-col xl:flex-row items-center gap-8"><div className="cadence-clock"><div className="cadence-hand" style={{transform:'translateX(-50%) rotate('+angle+'deg)'}}/><div className="cadence-hub"/></div><div><p className="dz-meta">Selected milestone gap</p><p className="dz-h2 text-5xl mt-3">{months?months+' mo':'START'}</p><p className="dz-body mt-3 max-w-xs">Interval between selected public milestones — not measured research generation time.</p></div></div></div>
  <div className="mt-10 grid grid-cols-6 lg:grid-cols-12 gap-x-4"><div className="col-span-6 lg:col-span-7 lg:col-start-5"><p className="dz-meta">Reading rule</p><p className="dz-body-strong mt-3">Release density alone does not establish faster research. The signal becomes stronger only when denser frontier releases coincide with independent capability growth, lower human intervention, persistent recursive gain and shorter validated R&D cycles.</p></div></div>
 </div></section>
}