import React,{useEffect,useMemo,useState}from'react';

type Metric={label:string,previous:number,current:number,unit?:string};
type M={year:number,date:string,name:string,org:string,type:'architecture'|'model'|'product'|'reasoning'|'open';why:string,url:string,era:'foundation'|'race',compareTo?:string,metrics?:Metric[],capabilities?:string[]};
const milestones:M[]=[
{year:2012.92,date:'2012',name:'AlexNet',org:'University of Toronto',type:'architecture',era:'foundation',why:'GPU-trained deep convolutional networks decisively changed large-scale vision.',url:'https://papers.nips.cc/paper/4824-imagenet-classification-with-deep-convolutional-neural-networks'},
{year:2016.07,date:'2016-01',name:'AlphaGo',org:'Google DeepMind',type:'reasoning',era:'foundation',why:'Deep neural networks, search and self-play defeated a professional Go player.',url:'https://www.nature.com/articles/nature16961'},
{year:2017.45,date:'2017-06',name:'Transformer',org:'Google',type:'architecture',era:'foundation',why:'Attention became the architecture behind the modern language-model era.',url:'https://arxiv.org/abs/1706.03762'},
{year:2018.45,date:'2018-06',name:'GPT',org:'OpenAI',type:'model',era:'foundation',why:'Generative pre-training demonstrated broad transfer from unsupervised language modelling.',url:'https://cdn.openai.com/research-covers/language-unsupervised/language_understanding_paper.pdf'},
{year:2019.12,date:'2019-02-14',name:'GPT-2',org:'OpenAI',type:'model',era:'foundation',why:'Scaling a transformer language model produced strong zero-shot behaviour.',url:'https://openai.com/index/better-language-models/'},
{year:2020.41,date:'2020-05-28',name:'GPT-3',org:'OpenAI',type:'model',era:'foundation',why:'Few-shot prompting became a central capability paradigm.',url:'https://openai.com/index/language-models-are-few-shot-learners/'},
{year:2022.91,date:'2022-11-30',name:'ChatGPT',org:'OpenAI',type:'product',era:'race',why:'The frontier becomes a mass interactive product. From here FEEDBACK expands calendar space to show the competitive race.',url:'https://openai.com/index/chatgpt/',capabilities:['dialogue','RLHF','mass deployment']},
{year:2023.20,date:'2023-03-14',name:'GPT-4',org:'OpenAI',type:'model',era:'race',why:'A major jump in difficult reasoning, exams and multimodality.',url:'https://openai.com/index/gpt-4-research/',compareTo:'GPT-3.5',metrics:[{label:'MMLU',previous:70,current:86.4,unit:'%'},{label:'HumanEval',previous:48.1,current:67,unit:'%'},{label:'GSM8K',previous:57.1,current:92,unit:'%'}],capabilities:['vision input','stronger reasoning','coding']},
{year:2023.53,date:'2023-07-11',name:'Claude 2',org:'Anthropic',type:'model',era:'race',why:'Anthropic strengthens the multi-lab frontier with gains in coding, mathematics and reasoning.',url:'https://www.anthropic.com/research/claude-2',compareTo:'Claude 1.3',metrics:[{label:'Bar exam MCQ',previous:73,current:76.5,unit:'%'}],capabilities:['100K context','coding','reasoning']},
{year:2023.93,date:'2023-12-06',name:'Gemini 1.0',org:'Google DeepMind',type:'model',era:'race',why:'A natively multimodal frontier family brings Google DeepMind fully into the race.',url:'https://blog.google/innovation-and-ai/technology/ai/google-gemini-ai/',capabilities:['native multimodality','Ultra / Pro / Nano']},
{year:2024.12,date:'2024-02-15',name:'Gemini 1.5 Pro',org:'Google DeepMind',type:'model',era:'race',why:'Long-context understanding becomes a new competitive axis.',url:'https://blog.google/innovation-and-ai/products/google-gemini-next-generation-model-february-2024/',compareTo:'Gemini 1.0 Ultra',capabilities:['1M-token context','multimodal reasoning','MoE efficiency']},
{year:2024.17,date:'2024-03-04',name:'Claude 3 Opus',org:'Anthropic',type:'model',era:'race',why:'Anthropic reports frontier performance across knowledge, reasoning and mathematics.',url:'https://www.anthropic.com/research/claude-3-family',compareTo:'Claude 2.1',capabilities:['vision','GPQA','stronger reasoning']},
{year:2024.36,date:'2024-05-13',name:'GPT-4o',org:'OpenAI',type:'model',era:'race',why:'Native real-time multimodality brings text, vision and audio into one flagship system.',url:'https://openai.com/index/hello-gpt-4o/',compareTo:'GPT-4',capabilities:['native audio','vision','lower latency']},
{year:2024.70,date:'2024-09-12',name:'o1',org:'OpenAI',type:'reasoning',era:'race',why:'Test-time reasoning opens a distinct scaling axis beyond pre-training.',url:'https://openai.com/index/learning-to-reason-with-llms/',compareTo:'GPT-4o',capabilities:['test-time reasoning','math','science','coding']},
{year:2024.99,date:'2024-12-26',name:'DeepSeek-V3',org:'DeepSeek',type:'open',era:'race',why:'A strong open model increases competitive pressure at the frontier.',url:'https://api-docs.deepseek.com/updates/',capabilities:['open weights','coding','math']},
{year:2025.05,date:'2025-01-20',name:'DeepSeek-R1',org:'DeepSeek',type:'reasoning',era:'race',why:'Open reasoning models demonstrate performance reported on par with o1 on math, code and reasoning tasks.',url:'https://deepseek.com/en/news/deepseek-r1/',compareTo:'DeepSeek-V3',capabilities:['large-scale RL','reasoning','open weights']},
{year:2025.60,date:'2025-08-07',name:'GPT-5',org:'OpenAI',type:'model',era:'race',why:'A unified system combines fast responses, deeper reasoning and routing for agentic work.',url:'https://openai.com/index/introducing-gpt-5/',compareTo:'GPT-4o / o-series',capabilities:['routing','agentic work','reasoning']},
{year:2026.31,date:'2026-04-23',name:'GPT-5.5',org:'OpenAI',type:'model',era:'race',why:'Greater autonomous work across coding, research, analysis and computer workflows.',url:'https://openai.com/index/introducing-gpt-5-5/',compareTo:'GPT-5',capabilities:['autonomous work','computer use','research']},
{year:2026.67,date:'2026-09-03',name:'GPT-6 Astra',org:'OpenAI',type:'model',era:'race',why:'A new frontier generation across computer use, software engineering, science and professional work.',url:'https://openai.com/index/gpt-6-astra/',compareTo:'GPT-5.5',capabilities:['computer use','science','software engineering']},
{year:2026.72,date:'2026-09-22',name:'GPT-6 Sol / Luna',org:'OpenAI',type:'model',era:'race',why:'Frontier capability spreads into faster and lower-cost members of the GPT-6 family.',url:'https://openai.com/index/introducing-gpt-6-sol-and-luna/',compareTo:'GPT-6 Astra',capabilities:['speed','cost efficiency','frontier family']}
];
const min=2012,max=2026.8,pivot=2022.91;
const pos=(y:number)=>y<=pivot?((y-min)/(pivot-min))*32:32+((y-pivot)/(max-pivot))*68;

function Delta({m}:{m:M}){const[open,setOpen]=useState(false);if(m.era!=='race')return null;return <div className="mt-8 border-t dz-rule pt-6"><button className="delta-toggle dz-meta bg-transparent dz-text border dz-rule px-4 py-3 cursor-pointer" onClick={()=>setOpen(v=>!v)}>{open?'CLOSE':'OPEN'} CAPABILITY DELTA {open?'−':'+'}</button>{open&&<div className="mt-6"><div className="flex flex-wrap gap-2">{m.capabilities?.map(x=><span key={x} className="dz-meta border dz-rule px-3 py-2">{x}</span>)}</div>{m.compareTo&&<p className="dz-meta mt-6">Compared with / {m.compareTo}</p>}{m.metrics?.length?<div className="mt-5 space-y-5">{m.metrics.map(q=><div key={q.label}><div className="flex justify-between gap-4 dz-meta"><span>{q.label}</span><span>{q.previous}{q.unit} → {q.current}{q.unit}</span></div><div className="delta-bars mt-2"><span style={{width:Math.min(100,q.previous)+'%'}}/><span className="current" style={{width:Math.min(100,q.current)+'%'}}/></div></div>)}</div>:<p className="dz-body mt-5">No clean like-for-like benchmark pair stored yet. New capability axes are shown without inventing a synthetic intelligence score.</p>}<p className="dz-meta mt-6">Benchmark comparisons are model-family specific. Do not compare bar lengths across unrelated tests.</p></div>}</div>}

export function FrontierCadence(){
 const[idx,setIdx]=useState(milestones.length-1);const[playing,setPlaying]=useState(false);
 useEffect(()=>{if(!playing)return;const id=window.setInterval(()=>setIdx(i=>i>=milestones.length-1?0:i+1),900);return()=>window.clearInterval(id)},[playing]);
 const m=milestones[idx]??milestones[milestones.length-1]!;const prev=idx?(milestones[idx-1]??null):null;
 const months=prev?Math.max(1,Math.round((m.year-prev.year)*12)):null;const angle=months==null?0:Math.min(months,48)/48*300-150;
 const density=useMemo(()=>milestones.map((item,i)=>({item,i})),[]);
 return <section id="cadence" className="border-t dz-rule relative z-10"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16 sm:py-24">
  <div className="grid grid-cols-6 lg:grid-cols-12 gap-x-4 gap-y-10"><div className="col-span-6 lg:col-span-3"><p className="dz-meta">TIME / Frontier race</p><p className="dz-body mt-5 max-w-xs">2012–2022 shows the foundations. At ChatGPT the calendar expands: the same physical width now holds only four years of the frontier race.</p></div><div className="col-span-6 lg:col-span-8 lg:col-start-5"><h2 className="dz-h2 text-5xl sm:text-7xl lg:text-8xl">Then the timeline opens.</h2><p className="dz-body-strong text-xl sm:text-2xl mt-8 max-w-3xl">Not an OpenAI chronology: a competitive frontier. OpenAI, Anthropic, Google DeepMind and DeepSeek enter the same compressed field.</p></div></div>
  <div className="mt-16 sm:mt-24 border-y dz-rule py-8"><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex gap-2"><button onClick={()=>setPlaying(!playing)} className="cadence-control dz-meta border dz-rule px-4 py-3 bg-transparent dz-text cursor-pointer">{playing?'PAUSE Ⅱ':'PLAY ▶'}</button><button onClick={()=>{setPlaying(false);setIdx(0)}} className="cadence-control dz-meta border dz-rule px-4 py-3 bg-transparent dz-text cursor-pointer">2012 ↺</button></div><p className="dz-meta">{m.date} / {m.org}</p></div>
   <div className="race-labels mt-10"><span>FOUNDATIONS / 2012—CHATGPT</span><span>FRONTIER RACE / CHATGPT—NOW</span></div>
   <div className={'cadence-track race-track mt-3 relative h-36 border-b dz-rule '+(m.era==='race'?'is-race':'')} aria-label="AI frontier timeline"><div className="race-pivot" style={{left:pos(pivot)+'%'}}><span>CHATGPT<br/>30.11.22</span></div>{density.map(d=><button key={d.i} onClick={()=>{setPlaying(false);setIdx(d.i)}} className="cadence-point" data-era={d.item.era} data-active={d.i===idx} style={{left:pos(d.item.year)+'%'}} aria-label={d.item.name}><span className="cadence-stem"/><span className="cadence-dot"/><span className="cadence-year">{d.i===0||d.i===density.length-1||d.item.date.slice(0,4)!==(density[d.i-1]?.item.date.slice(0,4)??'')?d.item.date.slice(0,4):''}</span></button>)}</div>
   <input className="cadence-range mt-8 w-full" type="range" min="0" max={milestones.length-1} value={idx} onChange={e=>{setPlaying(false);setIdx(Number(e.target.value))}} aria-label="Navigate AI milestones"/></div>
  <div className="grid lg:grid-cols-12 border-b dz-rule"><div className="lg:col-span-7 py-10 lg:pr-10 lg:border-r dz-rule"><p className="dz-meta">{String(idx+1).padStart(2,'0')} / {m.org} / {m.type}</p><h3 className="dz-h2 text-5xl sm:text-7xl mt-4">{m.name}</h3><p className="dz-body-strong text-xl mt-6 max-w-2xl">{m.why}</p><a href={m.url} target="_blank" rel="noreferrer" className="inline-block dz-meta mt-8 cadence-source">Primary source ↗</a><Delta m={m}/></div>
   <div className="lg:col-span-5 py-10 lg:pl-10 border-t lg:border-t-0 dz-rule flex flex-col sm:flex-row lg:flex-col xl:flex-row items-center gap-8"><div className="cadence-clock"><div className="cadence-hand" style={{transform:'translateX(-50%) rotate('+angle+'deg)'}}/><div className="cadence-hub"/></div><div><p className="dz-meta">Selected milestone gap</p><p className="dz-h2 text-5xl mt-3">{months?months+' mo':'START'}</p><p className="dz-body mt-3 max-w-xs">Editorial interval between selected frontier milestones — not measured research generation time.</p></div></div></div>
  <div className="mt-10 grid grid-cols-6 lg:grid-cols-12 gap-x-4"><div className="col-span-6 lg:col-span-7 lg:col-start-5"><p className="dz-meta">Reading rule</p><p className="dz-body-strong mt-3">The post-ChatGPT expansion is an editorial zoom, not proof that research itself accelerated. The hypothesis becomes interesting only when denser frontier releases coincide with independent capability growth, lower human intervention, persistent recursive gain and shorter validated R&D cycles.</p></div></div>
 </div></section>
}