import React,{useState}from'react';

type Stage={id:number;eyebrow:string;title:string;body:string;nodes:string[];accent?:boolean};
const stages:Stage[]=[
{id:1,eyebrow:'Today',title:'AI helps researchers.',body:'People choose the questions, judge the results and decide what should change. AI accelerates parts of the work.',nodes:['Human researcher','AI','Better AI']},
{id:2,eyebrow:'More automation',title:'AI does more of the research.',body:'Coding, experiments and evaluation can move from assistance toward autonomous execution. Human judgment still closes important gaps.',nodes:['Human direction','AI researcher','Better AI']},
{id:3,eyebrow:'The critical transition',title:'Better AI becomes a better researcher.',body:'An improvement matters recursively when it increases the system’s ability to produce the next useful improvement.',nodes:['AI','Better AI','Better researcher'],accent:true},
{id:4,eyebrow:'The feedback question',title:'Does the next cycle take less time?',body:'A loop is not an intelligence explosion by itself. The crucial signal is repeated acceleration: useful improvements arrive in shorter successive cycles.',nodes:['AI₁','AI₂','AI₃','AI₄'],accent:true}
];

export function TheLoop(){const[active,setActive]=useState(0);const s=stages[active];return <section id="loop" className="border-t dz-rule relative z-10"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16 sm:py-24">
<div className="grid grid-cols-6 lg:grid-cols-12 gap-x-4 gap-y-10"><div className="col-span-6 lg:col-span-3"><p className="dz-meta">01 / The loop</p><p className="dz-body mt-5 max-w-xs">Four steps explain the mechanism. No prediction is required.</p></div><div className="col-span-6 lg:col-span-8 lg:col-start-5"><h2 className="dz-h2 text-5xl sm:text-7xl lg:text-8xl">How could the loop close?</h2></div></div>
<div className="mt-16 sm:mt-24 border-y dz-rule grid lg:grid-cols-12 min-h-[32rem]">
<nav aria-label="Loop stages" className="lg:col-span-4 border-b lg:border-b-0 lg:border-r dz-rule">{stages.map((x,i)=><button key={x.id} onClick={()=>setActive(i)} aria-current={i===active?'step':undefined} className="loop-step w-full text-left px-5 sm:px-7 py-5 border-b dz-rule last:border-b-0 bg-transparent dz-text cursor-pointer" data-active={i===active}><span className="dz-meta">0{x.id} / {x.eyebrow}</span><span className="block dz-h3 text-xl sm:text-2xl mt-2">{x.title}</span></button>)}</nav>
<div className="lg:col-span-8 p-6 sm:p-10 lg:p-14 flex flex-col justify-between overflow-hidden"><div><p className="dz-meta">{s.eyebrow}</p><h3 className="dz-h2 text-4xl sm:text-6xl mt-4 max-w-3xl">{s.title}</h3><p className="dz-body-strong mt-6 max-w-2xl">{s.body}</p></div>
<div className="mt-14"><div className="loop-flow flex flex-wrap items-center gap-y-5">{s.nodes.map((node,i)=><React.Fragment key={node}><div className="loop-node" data-accent={s.accent&&i>0}>{node}</div>{i<s.nodes.length-1&&<div className="loop-arrow" aria-hidden="true"><span>→</span></div>}</React.Fragment>)}</div>{active===3&&<div className="mt-10 grid grid-cols-4 gap-2" aria-label="Illustrative cycle times"><div><span className="dz-meta">Cycle 1</span><div className="loop-time w-full"/></div><div><span className="dz-meta">Cycle 2</span><div className="loop-time w-3/4"/></div><div><span className="dz-meta">Cycle 3</span><div className="loop-time w-1/2"/></div><div><span className="dz-meta">Cycle 4</span><div className="loop-time w-1/3"/></div><p className="dz-meta col-span-4 mt-2">Illustration only — not a forecast.</p></div>}</div></div></div>
<div className="mt-10 grid grid-cols-6 lg:grid-cols-12 gap-x-4"><div className="col-span-6 lg:col-span-7 lg:col-start-5"><p className="dz-h3 text-2xl sm:text-4xl">If each useful improvement makes the next useful improvement easier — and the cycle keeps shortening — the dynamics have changed.</p><p className="dz-body mt-5">FEEDBACK watches for evidence of that transition. It does not assume that it will happen.</p></div></div>
</div></section>}
