export type EvidenceKind='observation'|'estimate'|'hypothesis'|'scenario';
export type Direction='supports'|'challenges'|'context';
export type IndicatorId='capability'|'closure'|'recursive-gain'|'generation-time';
export interface Source{id:string;title:string;publisher:string;publishedAt:string;url:string;sourceType:'evaluation'|'paper'|'survey'|'model';note?:string}
export interface Evidence{id:string;indicator:IndicatorId;kind:EvidenceKind;direction:Direction;title:string;summary:string;sourceIds:string[];observedAt?:string;confidence:'low'|'medium'|'high';limitation:string}
export interface Indicator{id:IndicatorId;symbol:'C'|'K'|'R'|'τ';label:string;question:string;status:'limited'|'developing'|'advanced'|'unknown';note:string;evidenceIds:string[]}

export const sources:Source[]=[
{id:'metr-opus55',title:"Summary of METR's predeployment evaluation of Claude Opus 5.5",publisher:'METR',publishedAt:'2026-09-22',url:'https://metr.org/blog/2026-09-22-claude-opus-5-5/',sourceType:'evaluation'},
{id:'metr-time-horizon',title:'Task-Completion Time Horizons of Frontier AI Models',publisher:'METR',publishedAt:'2026-05-08',url:'https://metr.org/time-horizons/',sourceType:'evaluation'},
{id:'chan-airda',title:'Measuring AI R&D Automation',publisher:'arXiv',publishedAt:'2026-03-06',url:'https://arxiv.org/abs/2603.03992',sourceType:'paper'},
{id:'chen-rsi-survey',title:'Recursive Self-Improvement in AI: From Bounded Self-Refinement to Autonomous Research Loops',publisher:'arXiv',publishedAt:'2026-09-06',url:'https://arxiv.org/abs/2607.07663',sourceType:'survey'},
{id:'srikanth-aide2',title:'Recursive self-improvement of AI research agents',publisher:'arXiv',publishedAt:'2026-09-22',url:'https://arxiv.org/abs/2609.26457',sourceType:'paper'},
{id:'ord-dynamics',title:'The Dynamics of Intelligence Explosions',publisher:'arXiv',publishedAt:'2026-08-14',url:'https://arxiv.org/abs/2608.14426',sourceType:'model'},
{id:'forethought-sie',title:'Will AI R&D Automation Cause a Software Intelligence Explosion?',publisher:'Forethought',publishedAt:'2025-03-26',url:'https://www.forethought.org/research/will-ai-r-and-d-automation-cause-a-software-intelligence-explosion',sourceType:'model'}
];

export const evidence:Evidence[]=[
{id:'c-metr-current',indicator:'capability',kind:'observation',direction:'supports',title:'Frontier systems can already automate limited AI R&D work',summary:'METR finds current frontier systems useful for researcher acceleration and limited R&D automation, while still showing weaknesses on hard long-horizon and open-ended research.',sourceIds:['metr-opus55'],observedAt:'2026-09-22',confidence:'high',limitation:'Capability evaluations do not directly measure end-to-end real-world automation.'},
{id:'c-horizon-growth',indicator:'capability',kind:'observation',direction:'supports',title:'Autonomous task horizons have risen rapidly',summary:'METR reports a strong historical increase in the length of software tasks frontier agents can complete autonomously.',sourceIds:['metr-time-horizon'],observedAt:'2026-05-08',confidence:'high',limitation:'Software task horizon is a proxy for research capability, not a direct measure of research judgement.'},
{id:'k-not-closed',indicator:'closure',kind:'observation',direction:'challenges',title:'Full AI R&D automation is not yet supported by current evidence',summary:'METR judges full automation unlikely for Claude Opus 5.5 and identifies foresight, prediction, autonomous feedback-loop creation and research judgement as remaining bottlenecks.',sourceIds:['metr-opus55'],observedAt:'2026-09-22',confidence:'high',limitation:'One frontier-model assessment does not characterize every lab system or private scaffold.'},
{id:'k-measurement-gap',indicator:'closure',kind:'observation',direction:'context',title:'Benchmark capability is not the same as real-world automation',summary:'Chan et al. argue that capability benchmarks alone can fail to capture actual AI R&D automation and propose operational measures such as researcher time allocation and capital share.',sourceIds:['chan-airda'],confidence:'high',limitation:'The paper proposes a measurement framework; many desired operational metrics are not yet publicly available.'},
{id:'k-direction-setting',indicator:'closure',kind:'observation',direction:'challenges',title:'Research direction-setting remains a human bottleneck',summary:'A 1,250-paper survey finds open-ended recursive improvement remains bounded and highlights choosing what deserves evaluation as a bottleneck not solved by stronger evaluators alone.',sourceIds:['chen-rsi-survey'],observedAt:'2026-09-06',confidence:'medium',limitation:'Survey-level synthesis combines heterogeneous systems and definitions.'},
{id:'r-aide2',indicator:'recursive-gain',kind:'observation',direction:'supports',title:'A research agent produced successive improvements to its own research process',summary:'AIDE² reports seven successive accepted improvements during an autonomous eight-day run, with gains transferring to held-out benchmarks.',sourceIds:['srikanth-aide2'],observedAt:'2026-09-22',confidence:'high',limitation:'The loop optimizes the agent harness under fixed evaluation budgets; it is not evidence of unbounded or accelerating recursive improvement.'},
{id:'r-bounded',indicator:'recursive-gain',kind:'observation',direction:'challenges',title:'Open-ended RSI remains bounded in the surveyed literature',summary:'Chen et al. distinguish industrial bounded self-refinement from open-ended RSI and report grounding, collapse and compute constraints across measured axes.',sourceIds:['chen-rsi-survey'],observedAt:'2026-09-06',confidence:'medium',limitation:'The field is moving quickly and survey coverage ends in 2026.'},
{id:'tau-theory',indicator:'generation-time',kind:'hypothesis',direction:'context',title:'Generation time is a decisive theoretical variable',summary:'Ord shows that feedback-loop generation time strongly shapes intelligence-explosion dynamics; singular growth requires generation time to rapidly approach zero.',sourceIds:['ord-dynamics'],confidence:'high',limitation:'This is a theoretical condition, not evidence that real AI R&D generation times are currently shrinking.'},
{id:'tau-no-trend',indicator:'generation-time',kind:'observation',direction:'challenges',title:'Current public evidence does not establish accelerating AI R&D cycles',summary:'METR states that available evidence is insufficient to distinguish consistent, accelerating or decelerating rates of improvement in AI R&D ability.',sourceIds:['metr-opus55'],observedAt:'2026-09-22',confidence:'high',limitation:'Private lab data could be richer than public evidence.'},
{id:'tau-sie-model',indicator:'generation-time',kind:'estimate',direction:'context',title:'Acceleration models depend on bottlenecks and diminishing returns',summary:'Forethought models how automated researchers, diminishing returns, experiment compute and retraining constraints could interact after full AI R&D automation.',sourceIds:['forethought-sie'],confidence:'medium',limitation:'Scenario model with consequential assumptions; it should not be treated as an observation of current dynamics.'}
];

export const indicators:Indicator[]=[
{id:'capability',symbol:'C',label:'Research capability',question:'Can AI do the work of an AI researcher?',status:'developing',note:'Material capability exists, but open-ended research judgement remains a constraint.',evidenceIds:['c-metr-current','c-horizon-growth']},
{id:'closure',symbol:'K',label:'Loop closure',question:'How much of the research loop can AI complete without us?',status:'developing',note:'Parts of the loop are automatable; current public evidence does not support full closure.',evidenceIds:['k-not-closed','k-measurement-gap','k-direction-setting']},
{id:'recursive-gain',symbol:'R',label:'Recursive gain',question:'Do improvements make AI better at producing the next improvement?',status:'developing',note:'Successive self-improvement has now been demonstrated in bounded research-agent settings.',evidenceIds:['r-aide2','r-bounded']},
{id:'generation-time',symbol:'τ',label:'Generation time',question:'Are successive improvement cycles getting faster?',status:'unknown',note:'Critical to the dynamics, but no robust public trend yet establishes repeated cycle-time compression.',evidenceIds:['tau-theory','tau-no-trend','tau-sie-model']}
];